### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by bizimunda** [benc-uk/python-demoapp#8]
**I am getting this error message**

Traceback (most recent call last):
  File "/Users/hamid/GitLab/Gitlab_Techworld_nina/python-demoapp/src/run.py", line 2, in <module>
    from app import create_app
  File "/Users/hamid/GitLab/Gitlab_Techworld_nina/python-demoapp/src/app/__init__.py", line 1, in <module>
    from flask import Flask
  File "/Users/hamid/GitLab/Gitlab_Techworld_nina/python-demoapp/src/.venv/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/Users/hamid/GitLab/Gitlab_Techworld_nina/python-demoapp/src/.venv/lib/python3.9/site-packages/jinja2/__init__.py)
make: *** [run] Error 1

**and this is what I have in my requirement file**

Flask==2.1.0
py-cpuinfo==7.0.0
psutil==5.8.0
gunicorn==20.1.0
black==20.8b1
flake8==3.9.0
pytest==7.1.2

**Comment by 3ika3ika** [comment]
@benc-uk do you have solution for that ? Would be highly appreciated !

**Comment by benc-uk** [comment]
Hi, This repo and app is really something I'm no longer supporting or using in anyway
Sorry

**Comment by leonidkiritschenko** [comment]
my solution from stackoverflow:

requirements.txt
```
Flask==2.1.0
py-cpuinfo==7.0.0
psutil==5.8.0
gunicorn==20.1.0
black==20.8b1
flake8==3.9.0
pytest==6.2.5
```

Sources:
1. https://stackoverflow.com/a/71735103/3388671
2. https://stackoverflow.com/a/69569206/3388671

**Comment by main-voice** [comment]
The solution from leonidkirischenko works well!

**Comment by Dustin-Wang** [comment]
Yeah, change the requirement.txt to 
Flask>=2.2.2
py-cpuinfo==7.0.0
psutil==5.8.0
gunicorn==20.1.0
black==20.8b1
flake8==3.9.0
pytest==6.2.2
fix the issue
